site_name: The DS2 Lab
#site_name: <html>D<font size=3em>S</font><sup>2</sup> Lab</html>
site_url: https://ds2lab.io
site_author: Yue Cheng
copyright: Copyright &copy; 2022 D<font size=1>S</font><sup>2</sup> Lab

nav:
  - Home: index.md
  - Team: team.md
  - Research: research.md
  - Publication: publication.md


theme:
  name: 'material'
  custom_dir: 'docs/overrides'
  logo: 'images/ds2lab_logo_blue_bg_white_fg.png'
  favicon: 'images/ds2lab_favicon_dark_bg.png'
  font: false

  icon:
    admonition:
      info: fontawesome/solid/bullhorn
      tip: fontawesome/solid/file-contract
      example: fontawesome/solid/person-chalkboard
      note: fontawesome/solid/book
      abstract: fontawesome/solid/database
      success: fontawesome/solid/graduation-cap
      quote: fontawesome/solid/book-open-reader


  features:
    - navigation.tabs

  palette:

    #Toggle Dark Mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: 'pink'
    accent: 'light green'
    toggle:
        icon: material/brightness-7
        name: Switch to light mode

    # Toggle Light Mode
  - media: "(prefers-color-scheme: light)"
    scheme: uva
    toggle:
        icon: material/brightness-4
        name: Switch to dark mode

#plugins:
#    - search
#    - encryptcontent:
#        title_prefix: '[Protected]'
#        summary: 'This Content is Password Protected'
#        placeholder: 'Click here to type the Password, then press Enter'
#        decryption_failure_message: 'Invalid Password'
#        encryption_info_message: 'This course content is password protected. Please enter the password.'


extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      toc_depth: 3
  - attr_list
  - meta

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mason-leap-lab
    - icon: fontawesome/brands/twitter
      link: https://twitter.com
